name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *'   # once daily at 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          owner: rasbt
          base: main
          head: main
